"""add_nome_to_users

Revision ID: 05edc097ec63
Revises: 7b13db6eebd5
Create Date: 2026-06-15 16:24:40.480375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05edc097ec63'
down_revision: Union[str, Sequence[str], None] = '7b13db6eebd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nome')
    # ### end Alembic commands ###
